name: Lambda Function

env:
  # environment vars
  ARTIFACT_NAME: lambdafn-${{ github.sha }}

on:
  push:
    branches: [serverless]

jobs:
  run_lambda:
    runs-on: ubuntu-latest
    name: Run Lambda Function
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2

      - name: Step 2 - Install AWS Cli
        run: sudo pip install awscli

      - name: Step 3 - Set correct aws environment
        run: |
          aws configure set region us-east-1
          aws configure set aws_access_key_id ${{ secrets.AWS_LAMBDA_USER_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_LAMBDA_USER_SECRET_ACCESS_KEY }}

      - name: zip files
        run : zip ${{ env.ARTIFACT_NAME }}.zip index.js

      - name: Step 4 - Upload Artifact/zip files to s3 bucket
        run: |
          aws s3 cp ${{ env.ARTIFACT_NAME }}.zip s3://${{ secrets.AWS_BUCKET }}/
      
      # - name: Step 5 - Update Function
        # aws deploy push --application-name csye6225-webapp --s3-location s3://${{ secrets.AWS_BUCKET }}/${{ env.ARTIFACT_NAME }}.zip --source /tmp/MyLocalDeploymentFolder/
      #   run: |
      #     aws deploy create-deployment \
      #     --application-name csye6225-webapp \
      #     --deployment-config-name CodeDeployDefault.AllAtOnce \
      #     --deployment-group-name csye6225-webapp-deployment \
      #     --file-exists-behavior OVERWRITE \
      #     --s3-location bucket=${{ secrets.AWS_BUCKET }},key=${{ env.ARTIFACT_NAME }}.zip,bundleType=zip \